# Job to run S3 tests automatically
apiVersion: batch/v1
kind: Job
metadata:
  name: s3-basic-test-job
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: s3-test-job
    spec:
      restartPolicy: Never
      containers:
      - name: s3-test
        image: amazon/aws-cli:latest
        command: ["/bin/bash", "/scripts/test-basic-operations.sh"]
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: test-s3-bucket
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: test-s3-bucket
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        - name: AWS_ENDPOINT_URL
          value: "https://s3.padmini.systems"
        - name: AWS_CLI_AUTO_PROMPT
          value: "off"
        volumeMounts:
        - name: bucket-config
          mountPath: /etc/bucket-config
          readOnly: true
        - name: test-scripts
          mountPath: /scripts
          readOnly: true
      volumes:
      - name: bucket-config
        configMap:
          name: test-s3-bucket
      - name: test-scripts
        configMap:
          name: s3-test-scripts
          defaultMode: 0755
  backoffLimit: 3
---
# Job for advanced S3 tests
apiVersion: batch/v1
kind: Job
metadata:
  name: s3-advanced-test-job
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: s3-advanced-test-job
    spec:
      restartPolicy: Never
      containers:
      - name: s3-advanced-test
        image: amazon/aws-cli:latest
        command: ["/bin/bash", "/scripts/test-advanced-operations.sh"]
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: test-s3-bucket
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: test-s3-bucket
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        - name: AWS_ENDPOINT_URL
          value: "https://s3.padmini.systems"
        - name: AWS_CLI_AUTO_PROMPT
          value: "off"
        volumeMounts:
        - name: bucket-config
          mountPath: /etc/bucket-config
          readOnly: true
        - name: test-scripts
          mountPath: /scripts
          readOnly: true
      volumes:
      - name: bucket-config
        configMap:
          name: test-s3-bucket
      - name: test-scripts
        configMap:
          name: s3-test-scripts
          defaultMode: 0755
  backoffLimit: 3